apiVersion: v1
kind: Service
metadata:
  name: pod-a
  namespace: poc
  labels:
    app: pod-a
spec:
  type: NodePort
  selector:
    app: pod-a
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30810
