apiVersion: v1
kind: Service
metadata:
  name: pod-b
  namespace: poc
  labels:
    app: pod-b
spec:
  type: NodePort
  selector:
    app: pod-b
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30820
